/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Bilibili: typeof import('./src/components/icons/Bilibili.vue')['default']
    BilibiliParse: typeof import('./src/components/dialogs/bilibiliParse.vue')['default']
    CopyButton: typeof import('./src/components/CopyButton.vue')['default']
    CustomHeaders: typeof import('./src/components/dialogs/customHeaders.vue')['default']
    DarkModeSwitcher: typeof import('./src/components/DarkModeSwitcher.vue')['default']
    Edit: typeof import('./src/components/icons/Edit.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Github: typeof import('./src/components/icons/Github.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Hot: typeof import('./src/components/Hot.vue')['default']
    Moon: typeof import('./src/components/icons/Moon.vue')['default']
    MoviePush: typeof import('./src/components/MoviePush.vue')['default']
    NewUser: typeof import('./src/components/admin/dialogs/newUser.vue')['default']
    Password: typeof import('./src/components/user/password.vue')['default']
    Person: typeof import('./src/components/icons/Person.vue')['default']
    Play: typeof import('./src/components/icons/Play.vue')['default']
    Player: typeof import('./src/components/Player.vue')['default']
    RoomList: typeof import('./src/components/RoomList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sun: typeof import('./src/components/icons/Sun.vue')['default']
    Trash: typeof import('./src/components/icons/Trash.vue')['default']
    UserRooms: typeof import('./src/components/admin/dialogs/userRooms.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
